version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    depends_on:
      - mosquitto
      - influxdb

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

  backend:
    build: ./backend
    container_name: medical_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
    depends_on:
      - mosquitto


  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: medical_mobile
    working_dir: /workspace/app_websocket
    volumes:
      - ./mobile/app_websocket:/workspace/app_websocket
      #- expo-node-modules_app_websocket:/workspace/app_websocket/node_modules
    ports:
      # Metro bundler / Expo
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      # Utile quando Expo gira dentro Docker e deve essere raggiunto dal telefono con Expo Go
      - EXPO_DEVTOOLS_LISTEN_ADDRESS= "0.0.0.0"
      - EXPO_PUBLIC_API_URL= "http://${HOST_IP}:${API_PORT}"
      - EXPO_PUBLIC_WS_URL= "ws://${HOST_IP}:${API_PORT}/ws"
      - EXPO_PUBLIC_SSE_URL= "http://${HOST_IP}:${API_PORT}/events"
    stdin_open: true
    tty: true
    #command: npx expo start --lan

volumes:
  expo-node-modules_app_websocket: